trigger:
  branches:
    include:
      - main

pool:
  name: 'himanshu'

steps:
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: 'INIT Backend Initialization'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ado-sc'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    backendAzureRmOverrideSubscriptionID: '81636ff2-7700-48a9-8aa6-9270d1bc92ae'
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmStorageAccountName: 'midsem26211'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  displayName: 'Plasn'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-var-file="$(System.DefaultWorkingDirectory)/terraform/env/dev/terraform.tfvars"'
    environmentServiceNameAzureRM: 'ado-sc'
    environmentAzureRmOverrideSubscriptionID: '81636ff2-7700-48a9-8aa6-9270d1bc92ae'
- task: TerraformTask@5
  displayName: 'Apply'
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve -var-file="$(System.DefaultWorkingDirectory)/terraform/env/dev/terraform.tfvars"'
    environmentServiceNameAzureRM: 'ado-sc'
    environmentAzureRmOverrideSubscriptionID: '81636ff2-7700-48a9-8aa6-9270d1bc92ae'
